// server/adapters/mock.js
//
// Mirrors the transcribe/synthesize signatures of server/adapters/revolab.js
// but never makes a network call. Used when MOCK=1, or per-request via
// ?mock=1 / x-mock: 1, so the UI can be developed and demoed without a
// live Revolab API key.

const MOCK_DELAY_MS = 300;

const MOCK_TRANSCRIPT = 'Bang, teh tarik satu, kurang manis.';

// A real ~0.3s silent MP3 (24kHz mono), generated with ffmpeg + libmp3lame
// and embedded as base64 so no binary asset file is needed.
const SILENT_MP3_BASE64 =
  'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYyLjEyLjEwMAAAAAAAAAAAAAAA//OEwAAAAAAAAAAAAEluZm8AAAAPAAAADwAABmAALS0tLS0tPDw8PDw8PEtLS0tLS1paWlpaWlppaWlpaWlpeHh4eHh4h4eHh4eHh5aWlpaWlpalpaWlpaW0tLS0tLS0w8PDw8PDw9LS0tLS0uHh4eHh4eHw8PDw8PDw////////AAAAAExhdmM2Mi4yOAAAAAAAAAAAAAAAACQDYAAAAAAAAAZga5fgdQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//NExAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExFMAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKYAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMu//NExKwAAANIAAAAADEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NExKwAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//NExKwAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV';

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Mock transcribe — same signature/shape as adapters/revolab.js#transcribe.
 * @param {{buffer: Buffer, filename?: string, mimetype?: string, language?: string}} input
 * @returns {Promise<{text: string, language: string, durationS: number, confidence: number, latencyMs: number}>}
 */
export async function transcribe({ buffer } = {}) {
  const start = Date.now();
  await delay(MOCK_DELAY_MS);
  return {
    text: MOCK_TRANSCRIPT,
    language: 'Malay',
    durationS: buffer && buffer.length ? Math.max(1, buffer.length / 32000) : 2.9,
    confidence: 0.95,
    latencyMs: Date.now() - start,
  };
}

/**
 * Mock synthesize — same signature/shape as adapters/revolab.js#synthesize.
 * @param {{text: string, voiceId: string, speed?: number, language?: string}} input
 * @returns {Promise<{audio: Buffer, contentType: string, durationS: number, latencyMs: number, requestId: string}>}
 */
export async function synthesize({ text } = {}) {
  const start = Date.now();
  await delay(MOCK_DELAY_MS);
  return {
    audio: Buffer.from(SILENT_MP3_BASE64, 'base64'),
    contentType: 'audio/mpeg',
    durationS: 0.3,
    latencyMs: Date.now() - start,
    requestId: `mock-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  };
}
